{
 "title": "Tomcat Exporter",
 "tags": [ "Tomcat" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(tomcat_session_active_total, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(tomcat_session_active_total{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Runtime Vendor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{vendor}}"
    }
   ]
  },
  {
   "title": "JVM Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{runtime}}"
    }
   ]
  },
  {
   "title": "JVM Runtime Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "JVM Uptime Hrs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(time()-(process_start_time_seconds{instance=\"$node\",job=\"$job\"})) /60/60"
    }
   ]
  },
  {
   "title": "JVM Classes Loaded",
   "type": "stat",
   "description": "The number of classes that are currently loaded in the JVM",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Application Contexts Started",
   "type": "graph",
   "description": "Indication if the lifecycle state of this context is STARTED",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_context_state_started{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Runs /sec over 1 min",
   "type": "graph",
   "description": "Count of JVM garbage collector runs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{instance=\"$node\",job=\"$job\"}[1m])*100",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC time in sec over 1 min",
   "type": "graph",
   "description": "Time spent in a given JVM garbage collector in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$node\",job=\"$job\"}[1m])*100",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Avg Time (ms) / GC 1 minute rate",
   "type": "graph",
   "description": "JVM garbage run times",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(jvm_gc_collection_seconds_sum{instance=\"$node\",job=\"$job\"}[1m])*100 / rate(jvm_gc_collection_seconds_count{instance=\"$node\",job=\"$job\"}[1m])*100)",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "JVM Threads Started Total",
   "type": "stat",
   "description": "Started thread count of a JVM",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_threads_started_total{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "JVM Threads Current",
   "type": "stat",
   "description": "Current thread count of a JVM",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "JVM Threads Peak",
   "type": "stat",
   "description": "Peak thread count of a JVM",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_threads_peak{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "JVM Threads Deadlocked",
   "type": "stat",
   "description": "Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_threads_deadlocked{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Tomcat Threads Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threads_max{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tomcat Thread Usage",
   "type": "gauge",
   "description": "Percentage of Total Threads compared to Max Threads per connector",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threads_total{instance=\"$node\",job=\"$job\"}/tomcat_threads_max{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tomcat Thread Usage Over Time",
   "type": "graph",
   "description": "Percentage of Total Threads compared to Max Threads per connector",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_total{instance=\"$node\",job=\"$job\"}/tomcat_threads_max{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tomcat Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "total {{name}}"
    },
    {
     "expr": "tomcat_threads_active_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "active {{name}}"
    }
   ]
  },
  {
   "title": "Thread State",
   "type": "graph",
   "description": "Current count of threads by state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Heap Max (MB)",
   "type": "stat",
   "description": "Max (bytes) of a given JVM memory area.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{instance=\"$node\",job=\"$job\",area=\"heap\"} /1024/1024"
    }
   ]
  },
  {
   "title": "NonHeap Max (MB)",
   "type": "stat",
   "description": "Max (bytes) of a given JVM memory area.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{instance=\"$node\",job=\"$job\",area=\"nonheap\"} /1024/1024"
    }
   ]
  },
  { "title": "Total JVM Memory", "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 81 } },
  {
   "title": "JVM Total Memory Committed (MB)",
   "type": "graph",
   "description": "Committed (bytes) of a given JVM memory area.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{instance=\"$node\",job=\"$job\"} /1024/1024",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "JVM Total Memory Used (MB)",
   "type": "graph",
   "description": "Used bytes of a given JVM memory area.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"$node\",job=\"$job\"} /1024/1024",
     "legendFormat": "{{area}}"
    }
   ]
  },
  { "title": "JVM Memory Pool", "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 90 } },
  {
   "title": "JVM Memory Pool Committed (MB)",
   "type": "graph",
   "description": "Committed bytes of a given JVM memory pool.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=\"$node\",job=\"$job\"} /1024/1024",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Used (MB)",
   "type": "graph",
   "description": "Used bytes of a given JVM memory pool.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$node\",job=\"$job\"} /1024/1024",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Max (MB)",
   "type": "graph",
   "description": "Max bytes of a given JVM memory pool.\n",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=\"$node\",job=\"$job\"} /1024/1024",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "Servlet Responses (if enabled)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Response Codes Min/Max in Range",
   "type": "graph",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "servlet_response_status_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{context}} HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Servlet Response Status Counts",
   "type": "graph",
   "description": "Number of requests for given context and status code",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "servlet_response_status_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{context}} HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Servlet Response Status /s over 1 min",
   "type": "graph",
   "description": "Number of requests for given context and status code",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(servlet_response_status_total{instance=\"$node\",job=\"$job\"}[1m])",
     "legendFormat": "{{context}} HTTP {{status}}"
    }
   ]
  },
  { "title": "Tomcat Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Sessions Created Total Counts",
   "type": "graph",
   "description": "Number of sessions created",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_session_created_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Created Total rate /sec over 1 min",
   "type": "graph",
   "description": "Number of sessions created",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_created_total{instance=\"$node\",job=\"$job\"}[1m])",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Rejected Total Counts",
   "type": "graph",
   "description": "Number of sessions rejected due to maxActive being reached",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_session_rejected_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Rejected Total  rate /sec over 1 min",
   "type": "graph",
   "description": "Number of sessions rejected due to maxActive being reached",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_rejected_total{instance=\"$node\",job=\"$job\"}[1m])",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Alive Time Max Counts",
   "type": "graph",
   "description": "Maximum time an expired session had been alive",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_session_alivetime_seconds_max{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Alive Time Max over 5 min (in seconds)",
   "type": "graph",
   "description": "Maximum time an expired session had been alive",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_alivetime_seconds_max{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Active Total Counts",
   "type": "graph",
   "description": "Number of active sessions",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_session_active_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Active Total rate /sec over 1 min",
   "type": "graph",
   "description": "Number of active sessions",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_active_total{instance=\"$node\",job=\"$job\"}[1m])",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Expired Total Counts",
   "type": "graph",
   "description": "Number of sessions that expired",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_session_expired_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Expired Total rate /sec over 1 min",
   "type": "graph",
   "description": "Number of sessions that expired",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 161 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_expired_total{instance=\"$node\",job=\"$job\"}[1m])",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Alive Time Avg  Counts",
   "type": "graph",
   "description": "Average time an expired session had been alive",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_session_alivetime_seconds_avg{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Alive Time Avg  /sec over 5 min",
   "type": "graph",
   "description": "Average time an expired session had been alive",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_alivetime_seconds_avg{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{context}}"
    }
   ]
  },
  { "title": "Tomcat Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 } },
  {
   "title": "Tomcat Connections Active Max Total",
   "type": "graph",
   "description": "Maximum number of concurrent connections served by this pool.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_connections_active_max{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tomcat Connections Active Total",
   "type": "graph",
   "description": "Number of connections served by this pool.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_connections_active_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Tomcat Request Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 } },
  {
   "title": "Requests /sec per 1 minutes",
   "type": "graph",
   "description": "The number of request served by this request processor",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_requestprocessor_request_count{instance=\"$node\",job=\"$job\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Request Errors /sec per 1 minutes",
   "type": "graph",
   "description": "The number of error request served by this request processor",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_requestprocessor_error_count{instance=\"$node\",job=\"$job\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Percent Errors/Requests",
   "type": "graph",
   "description": "Rate of errors compared to total requests for the request processor",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tomcat_requestprocessor_error_count{instance=\"$node\",job=\"$job\"}[1m])) by (instance,name) \n/ sum(rate(tomcat_requestprocessor_request_count{instance=\"$node\",job=\"$job\"}[1m])) by (instance,name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Request Received Bytes (MB) /sec over 5 min",
   "type": "graph",
   "description": "Number of bytes received by this request processor",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_requestprocessor_received_bytes{instance=\"$node\",job=\"$job\"}[5m]) /1024/1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Request Sent Bytes (MB) /sec over 5 min",
   "type": "graph",
   "description": "Number of bytes sent by this request processor",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_requestprocessor_sent_bytes{instance=\"$node\",job=\"$job\"}[5m]) /1024/1024 ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Tomcat JDBC (if enabled)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 211 } },
  {
   "title": "JDBC Max Connections",
   "type": "stat",
   "description": "Maximum number of active connections that can be allocated from this pool at the same time",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 212 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_jdbc_connections_max{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Tomcat JDBC Connections of Max",
   "type": "gauge",
   "description": "Percentage of total JDBC Connections used of Max limit. maxActive/maxTotal",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_jdbc_connections_total{instance=\"$node\",job=\"$job\"}/tomcat_jdbc_connections_max{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Tomcat JDBC Connections of Max Over Time",
   "type": "graph",
   "description": "Percentage of total JDBC Connections used of Max limit. maxActive/maxTotal",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "tomcat_jdbc_connections_total{instance=\"$node\",job=\"$job\"}/tomcat_jdbc_connections_max{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Total Connections",
   "type": "graph",
   "description": "Total number of connections in this pool",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 231 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_jdbc_connections_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Active Connections",
   "type": "graph",
   "description": "Number of active connections allocated from this pool",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 231 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_jdbc_connections_active_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Idle Connections",
   "type": "graph",
   "description": "Number of idle connections in this pool",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 238 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_jdbc_connections_idle_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Waiting Threads Total",
   "type": "graph",
   "description": "Number of threads waiting for connections from this pool",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 238 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_jdbc_waitingthreads_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Connections Borrowed /s over 5 min",
   "type": "graph",
   "description": "Number of connections borrowed from this pool",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 245 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_jdbc_connections_borrowed_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Connections Returned /s over 5 min",
   "type": "graph",
   "description": "Number of connections returned to this pool",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 245 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_jdbc_connections_returned_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Connections Created /s over 5 min",
   "type": "graph",
   "description": "Number of connections created by this pool",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 252 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_jdbc_connections_created_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Connections Released /s over 5 min",
   "type": "graph",
   "description": "Number of connections released by this pool",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 252 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_jdbc_connections_released_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Connections Reconnected /s over 5 min",
   "type": "graph",
   "description": "Number of reconnected connections by this pool",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_jdbc_connections_reconnected_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Connections Removed/Abandoned /sec over 5 min",
   "type": "graph",
   "description": "Number of abandoned connections that have been removed",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_jdbc_connections_removeabandoned_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Connections Released/Idle /s over 5 min",
   "type": "graph",
   "description": "Number of idle connections that have been released",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 266 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_jdbc_connections_releasedidle_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Failed Query Totals",
   "type": "table",
   "description": "Number of errors for give JDBC query",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 273 },
   "targets": [
    {
     "expr": "tomcat_jdbc_failedquery_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "JDBC Failed Query Details",
   "type": "table",
   "description": "Number of errors for give JDBC query",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 281 },
   "targets": [
    {
     "expr": "tomcat_jdbc_failedquery_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "JDBC query total duration over 1 min",
   "type": "graph",
   "description": "JDBC query duration",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 289 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_jdbc_query_seconds_sum{instance=\"$node\",job=\"$job\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "JDBC query count /s over 1 min",
   "type": "graph",
   "description": "JDBC query counts",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 289 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_jdbc_query_seconds_count{instance=\"$node\",job=\"$job\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "JDBC query average query duration value",
   "type": "graph",
   "description": "JDBC avg query duration",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 297 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_jdbc_query_seconds_sum{instance=\"$node\",job=\"$job\"} / tomcat_jdbc_query_seconds_count{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "JDBC query average query duration over 1 min",
   "type": "graph",
   "description": "JDBC avg query duration",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 297 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_jdbc_query_seconds_sum{instance=\"$node\",job=\"$job\"}[1m]) / rate(tomcat_jdbc_query_seconds_count{instance=\"$node\",job=\"$job\"}[1m]) ",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}